//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspFlex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ObjectName { get; set; }
        public string PlaceInstall { get; set; }
        public string Adress { get; set; }
        public string Category { get; set; }
        public int LineId { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
