//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspFlex
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectricityContainer : DbContext
    {
        public ElectricityContainer()
            : base("name=ElectricityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fider> FiderSet { get; set; }
        public virtual DbSet<Tp> TpSet { get; set; }
        public virtual DbSet<Line> LineSet { get; set; }
        public virtual DbSet<Customer> CustomerSet { get; set; }
    }
}
